title: "Slider-odos3d Lab"
description: "Hardware/3D/GRBL del slider Slider-odos3d + web legal (privacidad/t√©rminos) de la app Smart Timelapse AI."
theme: jekyll-theme-cayman
markdown: kramdown
lang: es-ES

# Project Pages (muy importante)
url: "https://odoslf.github.io"
baseurl: "/Slider-odos3d-Lab"

# SASS
sass:
  style: compressed
