title: "Slider-odos3d Lab"
description: "Repositorio público de hardware/3D/GRBL del slider Slider-odos3d + páginas legales (Privacidad/Términos) de la app Smart Timelapse AI."
theme: jekyll-theme-cayman
markdown: kramdown
lang: es-ES

# Project Pages (muy importante)
url: "https://odoslf.github.io"
baseurl: "/Slider-odos3d-Lab"

# SASS
sass:
  style: compressed
